version: '3.7'
services:
  app:
    build: .
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./lib:/usr/src/app/lib"
      - "./spec:/usr/src/app/spec"
      - "./.rubocop.yml:/usr/src/app/.rubocop.yml"
      - "./date_range_covers.gemspec:/usr/src/app/date_range_covers.gemspec"


